apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-text
        persistentVolumeClaim:
          claimName: text-claim
      containers:
        - name: log-output-writer
          image: melimet/log-output-writer:latest
          volumeMounts:
          - name: shared-text
          mountPath: /usr/src/app/files
        - name: log-output-reader
          image: melimet/log-output-reader:latest
          volumeMounts:
          - name: shared-text
          mountPath: /usr/src/app/files